### PR TITLE
Added codemirror, drag separator, async calls

### PR DESCRIPTION
**Pull request by MySpaceEmoCat**
Hi. Cool stuff. I've integrated Codemirror with a few plugins for it, and also updated your code to work better with async filesystem calls. I've also added a drag separator and moved some of the menu items into the top app menu.

lmk what you think famalamalam. Hang loose brosowski 🤙

### CODE REVIEW

**Comment by yikuansun** [comment]
Good stuff. Just a few issues to address:
 - file browser doesn't seem to work yet?
 - top-bottom mode doesn't work
 - autosave doesn't work (this just needs a minor fix)
 - need a way to access main menu (not too difficult to fix - main question is UX)
 - need button to toggle devTools for the webview (again, main question is where to put this button)

Otherwise, the changes are great! Let's talk about how we should tackle these issues, then I'll merge.

Edit: I've made npm install CodeMirror so we don't have to worry about manually downloading the package every time.

**Comment by MySpaceEmoCat** [comment]
I recommend reworking the main menu, because as it used to be, it entirely covers the main screen and there is no way to return to working on the project.

As for adding new functionality such as opening DevTools to the preview, I recommend putting it in the top menu. I scaffolded the template in main.js, but I recommend going over it to organize it better and to add a separate mode so it looks good on MacOS as well. You can use the Save option as a template on how to set it up, or I could do it too.

You can use Codemirror's NPM package, but I exported the library into a separate directory to reduce filesize. The entire Codemirror source is pretty heavy, and if you only use like 3-4 plugins and one theme its unnecessary, especially if you plan to distribute the entire app with it.

And lastly, what did you mean by the "top-bottom" mode and the file browser?

Oh and one more thing: the file list is better done with a separate section, since the <select> tag is poorly equipped to handle multilevel directory structures. Additionally, I recommend enabling browsing by a single file.

**Comment by yikuansun** [comment]
top-bottom mode can be found in the settings under layout; file browser is for choosing which file to open in the text editor. As you said, individual file opening is an option, but having some sort of within-app file selection might be faster. The select certainly wasn't perfect, but it worked.
As far as the npm package for CodeMirror, I prefer it over installing separate files due to more flexibility in the long run. So I'll keep it an npm package, at least for now.
The menu button was mainly for actually exiting the project completely and opening a new one. I will probably make a separate menu in the future.
I think the open devTools should be a button in the actual window in order to make it more obvious. Since it's an IDE and not a browser, devTools shouldn't be as hidden. Also, just in case you didn't know, devTools for the webview is called by a different function than the default menuitem, since it opens devTools for the parent BrowserWindow and does not access the webview's webContents. So the current devTools option in this pull request doesn't help the end user.

**Comment by yikuansun** [comment]
@MySpaceEmoCat Great work with implementing CodeMirror and the separator. How 'bout this: for this PR, let's work on making the CodeMirror and separator work whilst keeping the overall framework the same. As for the rest of the UX changes, we can work on them more gradually in the future. This way, we'll have a working version each time, without needing to do way too much merge stuff.
Sorry if it might seem like I'm discrediting your work... I'm not trying to, just think that some things would be better in separate PR's and commits. Hope you understand.

**Comment by yikuansun** [comment]
I've made the aforementioned fixes on a separate branch and merged that one into master.

**Pull request merged**
